AWSTemplateFormatVersion: 2010-09-09

# ------------------------------------------------------------------------------
# Parameter
# ------------------------------------------------------------------------------
Parameters:
  S3BucketName:
    Type: String
    Default: "data"


# ------------------------------------------------------------------------------
# Resourcec
# ------------------------------------------------------------------------------
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${S3BucketName}

# ------------------------------------------------------------------------------
# Output
# ------------------------------------------------------------------------------
Outputs:
  NOTE: 
    Value: !GetAtt
      - S3Bucket
  #  WebsiteURL:
  #    Value: !GetAtt 
  #      - S3Bucket
  #      - WebsiteURL
  #    Description: URL for website hosted on S3
  #  S3BucketSecureURL:
  #    Value: !Join 
  #      - ''
  #      - - 'https://'
  #        - !GetAtt 
  #          - S3Bucket
  #          - DomainName
  #    Description: Name of S3 bucket to hold website content
